publishdir = "_out"
baseurl = "https://ninefiveslabs.io"
title = "Nine Fives Labs"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    #author = "Nine Fives Labs"
    description = "Nine Fives Labs' website"
    keywords = "blog,developer,organization,nonprofit"
    avatarurl = "/horrible-nine-fives-labs.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    #footercontent = "Enter a text here."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false
    #custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ninefiveslabs/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/ninefiveslabs/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/ninefiveslabs/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin-in fa-2x"
    weight = 4
    url = "https://www.linkedin.com/company/nine-fives-labs/"
[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube fa-2x"
    weight = 4
    url = "https://www.youtube.com/channel/UCHj2NLqfEFHr1eNT4lt8g4w"

# Menu links
[[menu.main]]
    name = "Meetup"
    weight = 1
    url  = "/meetup"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"
