[build]
    publish = "_out"
    command = "hugo --buildFuture"

[context.production.environment]
  HUGO_VERSION = "0.68.3"

[context.deploy-preview]
    command = "hugo --buildFuture -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.68.3"
